= Retry policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-retry/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-retry/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^| -

|===

== Description

You can use the `retry` policy to replay requests when experiencing backend connection issues or if the response meets a given _condition_.

If the retry takes too long, relative to the `timeout` value, the request stops.

NOTE: To replay a request with a payload, the gateway stores it in memory. We recommend you avoid applying it to requests with a large payload.

=== Policy identifier

You can enable or disable the policy with policy identifier `retry`.

== Configuration

|===
|Property |Required |Description |Default |Example

.^|condition
^.^|X
|Condition to test to determine whether or not to retry the request (supports Expression Language)
^.^| -
^.^| {#response.status > 400}

.^|maxRetries
^.^|X
|Number of retries before failing (502 - Bad Gateway)
^.^| 1
^.^| -

.^|delay
^.^| -
|Time between each attempt
^.^| 0
^.^| -

.^|timeout
^.^|X
|Time after which an operation is considered a failure
^.^| 1000
^.^| -

.^|lastResponse
^.^|-
|Returns the last attempt response, even if it failed
^.^| false
^.^| -

|===


[source, json]
.Retry Policy example:
----
{
  "retry": {
    "condition": "{#response.status > 400}",
    "maxRetries": 3,
    "timeout": 1000
  }
}
----

== Errors

=== HTTP status code

|===
|Code |Reason

.^| ```502```
a|

Received in the following cases:

* No response satisfies the condition after `maxRetries`
* Technical errors when calling the backend (for example, connection refused, timeout)

|===
