version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
    gravitee: gravitee-io/gravitee@dev:2.0.1

# our single workflow, that triggers the setup job defined above
workflows:
    setup_build:
        when:
            not: << pipeline.git.tag >>
        jobs:
            - gravitee/setup_plugin-build-config

    setup_release:
        when:
            matches:
                pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
                value: << pipeline.git.tag >>
        jobs:
            - gravitee/setup_plugin-release-config
